services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "80:8000"
    env_file: ".env"

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      POSTGRES_DB: pantryPal
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s