@startuml
actor User

rectangle "Pantry Pal Application" {
    
    usecase "User Login" as UC1
    usecase "User Logout" as UC2
    usecase "Account Creation" as UC3
  
    
    usecase "Add Ingredients" as UC5
    usecase "Delete Ingredients" as UC6
    usecase "View Ingredients" as UC7
    usecase "Edit Ingredients" as UC8
    
    usecase "Generate Recipes" as UC9
    usecase "Save Generated Recipes" as UC10
    usecase "Remove Saved Recipes" as UC11
    
    usecase "Mark Recipe as Made" as UC12
    
    usecase "Share Recipes" as UC13
    usecase "View Recipe Details" as UC17
    
}

User --> UC1
User --> UC2
User --> UC3

User --> UC5
User --> UC6
User --> UC7
User --> UC8
User --> UC9
User --> UC10
User --> UC11
User --> UC12
User --> UC13

User --> UC17

@enduml