@startuml customerViewsProductPage

' === Style Tweaks ===

skinparam {
  Style StrictUML
  RoundCorner 5
  ParticipantPadding 10
  Padding 2
  SequenceStereotype {
    Font {
      Size 11
      Style plain
    }
  }
  Database {
	BorderColor #A80036
  }
}


' === Actors / Participants

actor "User" as user
participant "view/Ingredeints" as viewIngredients << HTML Page >>
participant "/Template" as template
participant "/Model" as model << Python >>
database "Database" as db <<Postgres>>


' === Interactions ===

user -> viewIngredients++ : User has signed in\n and now views the page

viewIngredients -> template++ : getAttribute("user")
template -> model : getUserById()
model -> template : return user
template -> viewIngredients : user


viewIngredients -> model++ : getAllIngredients()
model -> db++ : SELECT * FROM Ingredient
db -> model : Ingredient <<List>>
model -> template : Ingredient <<List>>

template -> viewIngredients : Display ingredients
viewIngredients -> user : Ingredients displayed to user.


@enduml