name: Django CI

on:
  push:
    branches: [ "DjangoAutoTesting" ]
  pull_request:
    branches: [ "DjangoAutoTesting" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
    services:
      postgres:
          image: postgres
          ports:
            - 5432:5432
          env:
            POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py makemigrations
        python manage.py makemigrations main
        python manage.py migrate
        python manage.py migrate main
        pytest
